function saveLog(opt)
% svdata = sprintf('%.3f\t\t%-8.3f\t%-8.3f\t%-8.3f\t%8.3f\n',...
%     GetSecs-opt.trBgn,...
%     opt.avatarX,...
%     opt.avatarY,...
%     opt.rewardAreaCenterX,...
%     opt.rewardAreaCenterY);
% fwrite(opt.fid,svdata);

opt.svdata = [opt.svdata;[...
    GetSecs-opt.trBgn,...
    opt.avatarX,...
    opt.avatarY,...
    opt.rewardAreaCenterX,...
    opt.rewardAreaCenterY
    ]];
end

